

source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.3"
gem "sinatra",  "~> 3.0"

gem "opentelemetry-sdk", "~> 1.5.0"
gem "opentelemetry-exporter-otlp", "~> 0.29.0"
gem "opentelemetry-instrumentation-all", "~> 0.63.0"
